# Generated by Django 5.1.7 on 2025-03-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
