# Generated by Django 5.1.7 on 2025-03-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_member_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['firstname', 'lastname']},
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
